language: python

jobs:
  include:
    - name: "Atari with Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install:

        - export AUDIODEV=null
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - export pz_module=atari
        - pip install multi_agent_ale_py pygame==2.0.0.dev10
        - sudo apt-get install unrar
        - pip3 install AutoROM
        - AutoROM -v
    - name: "Atari with Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install:

        - export AUDIODEV=null
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - pip install multi_agent_ale_py pygame==2.0.0.dev10
        - export pz_module=atari
        - sudo apt-get install unrar
        - pip3 install AutoROM
        - AutoROM -v
    - name: "Atari with Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install:

        - export AUDIODEV=null
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - pip install multi_agent_ale_py pygame==2.0.0.dev10
        - sudo apt-get install unrar
        - export pz_module=atari
        - pip3 install AutoROM
        - AutoROM -v

    - name: "Classic with Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install:
        - pip install python-chess rlcard>=0.2.5  python-shogi  hanabi_learning_environment
        - export pz_module=classic
    - name: "Classic with Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install:
        - pip install python-chess rlcard>=0.2.5  python-shogi  hanabi_learning_environment
        - export pz_module=classic
    - name: "Classic with Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install:
        - pip install python-chess rlcard>=0.2.5  python-shogi  hanabi_learning_environment
        - export pz_module=classic

    - name: "Butterfly with Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install:
        - pip install pygame==2.0.0.dev10 pymunk==5.6.0
        - export pz_module=butterfly
    - name: "Butterfly with Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install:
        - pip install pygame==2.0.0.dev10 pymunk==5.6.0
        - export pz_module=butterfly
    - name: "Butterfly with Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install:
        - pip install pygame==2.0.0.dev10 pymunk==5.6.0
        - export pz_module=butterfly

    - name: "mpe with Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install:
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
        - pip install pyglet
        - export pz_module=mpe
    - name: "mpe with Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install:
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
        - pip install pyglet
        - export pz_module=mpe
    - name: "mpe with Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install:
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
        - pip install pyglet
        - export pz_module=mpe
    - name: "sisl with Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install:
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
        - pip install  pygame==2.0.0.dev10 opencv-python scikit-image>=0.16.2 gym[box2d]>=0.17.2 box2d-py
    - name: "sisl with Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install:
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
        - pip install  pygame==2.0.0.dev10 opencv-python scikit-image>=0.16.2 gym[box2d]>=0.17.2 box2d-py
    - name: "sisl with Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install:
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
        - pip install  pygame==2.0.0.dev10 opencv-python scikit-image>=0.16.2 gym[box2d]>=0.17.2 box2d-py
    - name: "MAgent with Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install:
        - export AUDIODEV=null
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - pip install magent pygame==2.0.0.dev10
        - export pz_module=magent
    - name: "MAgent with Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install:
        - export AUDIODEV=null
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - pip install magent pygame==2.0.0.dev10
        - export pz_module=magent
    - name: "MAgent with Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install:

        - export AUDIODEV=null
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - pip install magent pygame==2.0.0.dev10
        - export pz_module=magent


    - name: "Atari with Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - swig
            - unrar
            - llvm
      language: shell
      before_install:
        - export pz_module=atari
        - pip install multi_agent_ale_py pygame==2.0.0.dev10

    - name: "Classic with Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      language: shell
      before_install:
        - export pz_module=classic
        - pip install python-chess rlcard>=0.2.5  python-shogi  hanabi_learning_environment

    - name: "Butterfly with Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      language: shell
      before_install:
        - export pz_module=butterfly
        - export pz_render=False
        - pip install pygame==2.0.0.dev10 pymunk==5.6.0

    - name: "mpe with Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      language: shell
      before_install:
        - export pz_module=mpe
        - pip install pyglet

    - name: "sisl with Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - swig
      language: shell
      before_install:
        - export pz_module=sisl
        - export pz_render=False
        - pip install  pygame==2.0.0.dev10 opencv-python scikit-image>=0.16.2 gym[box2d]>=0.17.2 box2d-py

    - name: "MAgent with Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - swig
            - unrar
            - llvm
      language: shell
      before_install:
        - export pz_module=magent
        - pip install magent pygame==2.0.0.dev10


install:
  - pip3 install flake8

script:
  - chmod +x test.sh
  - ./test.sh
  - cat test_output.txt
