language: python

jobs:
  include:
    - name: "Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install: 
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
    - name: "Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install: 
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
    - name: "Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install: 
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
    - name: "Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - swig
      language: shell


install:
  - pip3 install flake8
  - pip3 install -r requirements.txt
  - pip3 install AutoROM
  - AutoROM -v

script:
  - bash test.sh