language: python

jobs:
  include:
    - name: "Atari with Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install: 
        - ./linux_install.sh
        - export pz_module=atari
    - name: "Atari with Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install: 
        - ./linux_install.sh
        - export pz_module=atari
    - name: "Atari with Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install: 
        - ./linux_install.sh
        - export pz_module=atari

    - name: "Classic with Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install: 
        - ./linux_install.sh
        - export pz_module=classic
    - name: "Classic with Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install: 
        - ./linux_install.sh
        - export pz_module=classic
    - name: "Classic with Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install: 
        - ./linux_install.sh
        - export pz_module=classic

    - name: "Gamma with Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install: 
        - ./linux_install.sh
        - export pz_module=gamma
    - name: "Gamma with Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install: 
        - ./linux_install.sh
        - export pz_module=gamma
    - name: "Gamma with Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install: 
        - ./linux_install.sh
        - export pz_module=gamma

    - name: "mpe with Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install: 
        - ./linux_install.sh
        - export pz_module=mpe
    - name: "mpe with Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install: 
        - ./linux_install.sh
        - export pz_module=mpe
    - name: "mpe with Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install: 
        - ./linux_install.sh
        - export pz_module=mpe

    - name: "sisl with Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install: 
        - ./linux_install.sh
        - export pz_module=sisl
    - name: "sisl with Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install: 
        - ./linux_install.sh
        - export pz_module=sisl
    - name: "sisl with Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install: 
        - ./linux_install.sh
        - export pz_module=sisl


    - name: "Atari with Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - swig
            - unrar
      language: shell
      before_install: 
        - export pz_module=atari

    - name: "Classic with Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - swig
            - unrar
      language: shell
      before_install: 
        - export pz_module=classic

    - name: "Gamma with Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - swig
            - unrar
      language: shell
      before_install: 
        - export pz_module=gamma

    - name: "mpe with Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - swig
            - unrar
      language: shell
      before_install: 
        - export pz_module=mpe

    - name: "sisl with Python 3 on macOS"
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - swig
            - unrar
      language: shell
      before_install: 
        - export pz_module=sisl


install:
  - pip3 install flake8
  - pip3 install -r requirements.txt
  - pip3 install AutoROM
  - AutoROM -v

script:
  - ./test.sh