language: python

jobs:
  include:
    - name: "Python 3.6 on Linux"
      services:
        - xvfb
      python: 3.6
      before_install: 
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
    - name: "Python 3.7 on Linux"
      services:
        - xvfb
      python: 3.7
      before_install: 
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
    - name: "Python 3.8 on Linux"
      services:
        - xvfb
      python: 3.8
      before_install: 
        - sudo apt-get install swig
        - sudo apt install freeglut3-dev
    - name: "Python 3 on macOS"
      services:
        - xvfb
      os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - swig
      language: shell


install:
  - pip3 install flake8
  - pip3 install -r requirements.txt

script:
  - bash test.sh